---
- name: "Create a temporary rhel builder"
  hosts: localhost
  connection: local
  tasks:
  - name: "vagrant start a rhel8 builder"
    shell: "vagrant up"
  - name: "save old ssh config file"
    shell: "vagrant ssh-config >  builder.conf"

- name: Build openstack components
  hosts: builders
  tasks:
     - name: Build the scl
       vars:
          - version: "1.0.0"
          - project:  "awxrpm"
          - organisation: miracle
          - sclname: "awxrpm"
          - repo_url: "https://github.com/ansible/awx.git"
       include_role:
         name:  miracle-ansible-role-pipfreeze2scl 
  become: True



- name: "Playing with Ansible and Git"
  hosts: localhost
  connection: local
  tasks:
  - name: "vagrant destroy"
    shell: "echo vagrant destroy -f"
