---














- name: "Create a temporary rhel builder"
  hosts: localhost
  connection: local
  tasks:
  
  - name: "Clean up rhel subscriptions"
    shell: "vagrant up"
  - name: "vagrant start a rhel8 sclbuilder"
    shell: "vagrant up"
  - name: "save old ssh config file"
    shell: "vagrant ssh-config >  builder.conf"
  - name: "copy key to servers"
    shell: "vagrant scp ~/.ssh/scldistro scldistro"






- name: Build openstack components
  hosts: sclbuilder
  tasks:
    - name: Build the scl
      vars:
         - version: "awxrpm"
         - project:  "awx"
         - project_dir: "/opt/awx"
         - organisation: "miracle"
         - scl_version: "19.4.0"
         - scl_release: "1"
         - scl_description: "A precompiled package which installed the requirements for running the service"
         - requirementsfile: "http://repos.pip2scl.dk/awx.requirements.txt"
         - requirementfile: "http://repos.pip2scl.dk/awx.requirements.txt"
         - repo_url: "https://github.com/ansible/awx.git"
         - branch: "19.4.0"
      include_role:
         name:  miracle-ansible-role-pipfreeze2scl 
  become: True

